config/routes.rb
Rails.application.routes.draw do
  resources :votes

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :stops

  get 'pages/home'

  resources :routes
  resources :waypoints

   root 'routes#index'

 devise_scope :user do
  get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_facebook_session
  end

end

app/models/stop.rb
class Stop < ActiveRecord::Base
  validates :description, length: { maximum: 140 }
  #Image Uploader
  mount_uploader  :stop_image, StopImageUploader
  
  #Relationship with stops and waypoints
  has_many :waypoints
  has_many :routes, through: :waypoints

  #test

  # Relationship with categories
  has_many :stop_categories
  has_many :categories, through: :stop_categories 
end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
  before_action :set_stop, only: [:show, :edit, :update, :destroy]

  # GET /stops
  # GET /stops.json
  def index
    @stops = Stop.all

  end

  # GET /stops/1
  # GET /stops/1.json
  def show
    @stop = Stop.find(params[:id])
  end

  # GET /stops/new
  def new
    @stop = Stop.new
  end

  # GET /stops/1/edit
  def edit
    @categories = Category.all
  end

  # POST /stops
  # POST /stops.json
  def create
    @stop = Stop.new(stop_params)

    
   

    
    respond_to do |format|
     # if @stop.save
     @stop.save!(validate: false)
     if true
        Waypoint.create(route_id: params[:route_id] , stop_id: @stop.id)
        #print out category id or name here
        category = params[:category]
        #once printed save it (stop category)
        StopCategory.create(category_id: category, stop_id:  @stop.id)
        format.html { redirect_to @stop, notice: 'Stop was successfully created.' }
        format.json { render :show, status: :created, location:@stop }
      else

        format.html { render :new }
        format.json { render json: @stop.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /stops/1
  # PATCH/PUT /stops/1.json
  def update

    respond_to do |format|
      if @stop.update(stop_params)
        format.html { redirect_to @stop, notice: 'Stop was successfully updated.' }
        format.json { render :show, status: :ok, location: @stop }
      else
        format.html { render :edit }
        format.json { render json: @stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stops/1
  # DELETE /stops/1.json
  def destroy
    @stop.destroy
    respond_to do |format|
      format.html { redirect_to stops_url, notice: 'Stop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stop
      @stop = Stop.find(params[:id])
    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def stop_params
      params.require(:stop).permit(:name, :description, :stop_image, :stop_lat, :stop_long)
    end
end

app/helpers/stops_helper.rb
module StopsHelper
end

app/views/stops/_form.html.erb
<%= form_for(@stop) do |f| %>
  <% if @stop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stop.errors.count, "error") %> prohibited this stop from being saved:</h2>

      <ul>
      <% @stop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
<div class="field">
    <%= f.label :stop_image %><br>
    <%= f.file_field :stop_image %>
  </div>






<select name="category" id=" " >
        
        <option value="" disabled selected> Select a Category </option>

        <% Category.all.each do |category| %>
        <option value="<%= category.id %>"> <%= category.name %> </option>
      <% end %>
    </select>




  


  
    <div class="field">
        <%= f.label :stop_lat %><br>
        <%= f.number_field :stop_lat %>
    </div>
        <div class="field">
        <%= f.label :stop_long %><br>
        <%= f.number_field :stop_long %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %> 

app/views/stops/edit.html.erb
<h1>Editing stop</h1>

<%= render 'form' %>

<%= link_to 'Show', @stop %> |
<%= link_to 'Back', stops_path %>

app/views/stops/index.html.erb
<h1>Listing stops</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Stop image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stops.each do |stop| %>
      <tr>
        <td><%= stop.name %></td>
        <td><%= stop.description %></td>
        <td><%= stop.stop_image %></td>
        <td><%= link_to 'Show', stop %></td>
        <td><%= link_to 'Edit', edit_stop_path(stop) %></td>
        <td><%= link_to 'Destroy', stop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stop', new_stop_path %>

app/views/stops/new.html.erb
<h1>New stop</h1>

<%= render 'form' %>

<%= link_to 'Back', stops_path %>

app/views/stops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stop.name %>
</p>

	<img src="<%= @stop.stop_image_url(:thumb_600) %>" >



<p>
  <strong>Description:</strong>
  <%= @stop.description %>
</p>

<%= link_to 'Edit', edit_stop_path(@stop) %> |
<%= link_to 'Back', stops_path %>

app/views/stops/stop_form_backup.html.erb
<%= form_for(@stop) do |f| %>
  <% if @stop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stop.errors.count, "error") %> prohibited this stop from being saved:</h2>

      <ul>
      <% @stop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
<div class="field">
    <%= f.label :stop_image %><br>
    <%= f.file_field :stop_image %>
  </div>






<select name="category" id=" " >
        
        <option value="" disabled selected> Select a Category </option>

        <% @categories.each do |category| %>
        <option value="<%= category.id %>"> <%= category.name %> </option>
      <% end %>
    </select>




  


  
    <div class="field">
        <%= f.label :stop_lat %><br>
        <%= f.number_field :stop_lat %>
    </div>
        <div class="field">
        <%= f.label :stop_long %><br>
        <%= f.number_field :stop_long %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %> 