config/routes.rb
Rails.application.routes.draw do
  resources :votes

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :stops

  get 'pages/home'

  resources :routes
  resources :waypoints

   root 'routes#index'

 devise_scope :user do
  get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_facebook_session
  end

end

app/models/route.rb
class Route < ActiveRecord::Base		
	validates :description, length: { maximum: 140 }
	validates :title, :description,presence:true
	has_many :waypoints
	has_many :stops, through: :waypoints	
	has_many :votes
	mount_uploader  :route_image, RouteImageUploader


def score
	votes.sum(:score)
end

def positive_votes
	votes.where(score: 1).count
end

def negative_votes
	votes.where(score: -1).count
end


end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  # GET /routes
  # GET /routes.json
  def index
    @routes = Route.all
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
  @stops = Stop.all
  @stop = Stop.new
  @waypoint = Waypoint.new(route:  @route)
  @categories = Category.all
  @users = User.all 

  end

  # GET /routes/new
  def new
    @route = Route.new
  end


  # GET /routes/1/edit
  def edit
  end


  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)

    respond_to do |format|
      if @route.save
        format.html { redirect_to @route, notice: 'Route was successfully created.' }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: 'Route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:title, :description, :route_image, :stop_id)
    end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_form.html.erb
<%= form_for(@route) do |f| %>
  <% if @route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% @route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :route_image %><br>
    <%= f.file_field :route_image %>
  </div>
<%# here is the stop_id to add to the route %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

  

app/views/routes/edit.html.erb
<h1>Editing route</h1>

<%= render 'form' %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<div class="row  tag-wrapper">
  <span class="tagline">Inside Berlin</span>
    <span class="subtitle">Discover unique guided routes with awesome spots in Berlin</span>
</div>


<div class="row ">


    <div class="row ">
      <% @routes.each do |route| %>
        <div class="route-wrapper small-12 medium-4 large-4 columns">
          <div class="route_item">
                    


                
                  <a  href=" <%= route_path(route) %> ">

                        <figure>
                          <div class="relative">
                            <img  src="<%= route.route_image_url(:thumb) %>" >
                            <figcaption>


                            </figcaption>
                        </div>

                        </figure>
                            <h3> <%= route.title %></h3>
                  </a>
                
                 <div class="route_img_icons column">
                    <div class="small-4 columns"><%= fa_icon "clock-o" %><span class="icons-text">Duration</span></div>
                    <div class="small-4 columns"><%= fa_icon "thumbs-o-up" %><span class="icons-text">Likes</span></div>
                    <div class="small-4 columns"><%= fa_icon "share" %><span class="icons-text">Share</span></div>
                  </div>

                            <p><%= route.description %></p>              
     
                



                                            <%-# comment -%>
                                              <% if false %> 

                  <%= link_to 'Edit', edit_route_path(route) %>
                                                <%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %>
                                                   
                                                <%= link_to 'Edit', edit_route_path(route) %>
                                                <%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %>

          <%= link_to 'New Route', new_route_path %>
          
                                              <% end %>
                                            <%-# comment -%>



          </div>
        </div>
      <% end %>
    </div>


  </div>

app/views/routes/index_backup.html.erb
<div class="row  tag-wrapper">
  <span class="tagline">Inside Berlin</span>
    <span class="subtitle">Discover unique guided routes with awesome spots in Berlin</span>
</div>


<div class="row ">


    <div class="row ">
      <% @routes.each do |route| %>
        <div class="route-wrapper small-12 medium-4 large-4 columns">
          <div class="route_item">
                    


                
                  <a  href=" <%= route_path(route) %> ">
                          <div class="relative">
                          <img  src="<%= route.route_image_url(:thumb) %>" >       
                   
                            <h3> <%= route.title %></h3>
                          </div>
                  </a>
                
                 <div class="route_img_icons column">
                    <div class="small-4 columns"><%= fa_icon "clock-o" %><span class="icons-text">Duration</span></div>
                    <div class="small-4 columns"><%= fa_icon "thumbs-o-up" %><span class="icons-text">Likes</span></div>
                    <div class="small-4 columns"><%= fa_icon "share" %><span class="icons-text">Share</span></div>
                  </div>
                            <p><%= route.description %></p>              
     
                



                                            <%-# comment -%>
                                              <% if false %> 
                                              <p><%= route.description %></p>

                                                   
                                                <%= link_to 'Edit', edit_route_path(route) %>
                                                <%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %>
                                              <% end %>
                                            <%-# comment -%>



          </div>
        </div>
      <% end %>
    </div>
          <%= link_to 'New Route', new_route_path %>


  </div>

app/views/routes/index_flat.html.erb

<div class="row  tag-wrapper">
  <span class="tagline">Inside Berlin</span>
    <span class="subtitle">Discover unique guided routes with awesome spots in Berlin</span>
</div>

<div class="row ">
  <% @routes.each do |route| %>
    <div class="route-wrapper small-12 medium-4 large-4 columns no-padding">
      <div class="route_item">
                <h3> <%= route.title %></h3>


            
              <a href=" <%= route_path(route) %> ">
                <figure>
                      <img src="<%= route.route_image_url(:thumb) %>" >       
                      <figcaption>
                        <h3> <%= route.title %></h3>
                        <p><%= route.description %></p>

                        <div class="route_img_icons column">
                          <div class="small-4 columns"><%= fa_icon "clock-o" %><span class="icons-text">Duration</span></div>
                          <div class="small-4 columns"><%= fa_icon "thumbs-o-up" %><span class="icons-text">Likes</span></div>
                          <div class="small-4 columns"><%= fa_icon "share-alt" %><span class="icons-text">Share</span></div>
                        </div>

                      </figcaption> 
                </figure>
              </a>
            
 
            



                                        <%-# comment -%>
                                          <% if false %> 
             <div class="route_img_icons column">
                <div class="small-4 columns"><%= fa_icon "clock-o" %><span class="icons-text">Duration</span></div>
                <div class="small-4 columns"><%= fa_icon "thumbs-o-up" %><span class="icons-text">Likes</span></div>
                <div class="small-4 columns"><%= fa_icon "share-alt" %><span class="icons-text">Share</span></div>
              </div>
              <p><%= route.description %></p>












                                               
                                            <%= link_to 'Edit', edit_route_path(route) %>
                                            <%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %>
                                          <% end %>
                                        <%-# comment -%>
      </div>
    </div>
  <% end %>
</div>
      <%= link_to 'New Route', new_route_path %>



app/views/routes/new.html.erb
<h1>New route</h1>

<%= render 'form' %>

<%= link_to 'Back', routes_path %>

app/views/routes/show.html.erb
<div class="row">
	<div class="small-12 medium-12 large-12 columns page-wrapper">
			<script>route_id = <%= @route.id %></script>
			<% if notice %>
				<p id="notice"><%= notice %></p>
			<% end %>

	<div class="row">

		<div class="stop-title small-12 medium-12 large-12 columns">
			 <h1><%= @route.title %></h1> <hr>
		</div>	


			<div class="small-12 medium-6 large-6 columns">
				<div class="description">
				  <% @route.stops.each do |stop| %>
					  <div class="hiddenName">
						<%= stop.name %>
				    </div>
				  <% end %>
			      <h3 class="show-name showname"></h3>
			    	<p class="show-description"></p> 
			    	<h5>Category:  </h5>
				</div>
			</div>

		
		<div class="small-12 medium-6 large-6 columns">

			<div class="route-desc-desktop small-12 medium-12 large-12 columns">
		  	<p> <%= @route.description %> </p>
			</div>

			<div class="stop-info-wrapper small-12 medium-12 large-12 columns">

				<div class="small-4 medium-4 large-4 columns stop-info ">
				<%= fa_icon "clock-o" %>&nbsp;&nbsp;Aprox time
				</div>			
				<div class="small-4 medium-4 large-4 columns stop-info add-left-border">
				<%= fa_icon "thumbs-o-up" %>&nbsp;&nbsp;23.K Votes
				</div>
				<div class="small-4 medium-4 large-4 columns stop-info add-left-border ">
				<%= fa_icon "share" %>&nbsp;&nbsp;Share
				</div>
			
			</div>

		</div>

	</div>







	<div class="row">
		<div class="small-12 medium-6 large-6 columns">

				<ul id="stops-carousel" data-orbit data-options="timer_speed:8000;
																												pause_on_hover:false;
		    																								timer:true;">
				  <% @route.stops.each do |stop| %>
				  <li>
				    <img src="<%= stop.stop_image_url(:thumb_600) %>" alt="<%= stop.name %>" />
				    <div class="orbit-caption">
						<%= stop.name %>
					<div class="hiddenDescriptions">
						<%= stop.description %>	
					</div>
				    </div>
				  </li>
				  
				  <% end %>
				</ul>
		</div>

		<div class="map-container small-12 medium-6 large-6 columns ">
				<div class="map-width "></div>	
				<div id="map-canvas">	</div>
		</div>

		<div class="description-phone small-12 medium-6 large-6 columns">
			<p class="show-description"></p>
		</div>

	</div>







	<div class="row">
			<div class="small-12 medium-6 large-6 columns">
				<div class="voting">
					<h3 class="text-center ">Vote for this Route:</h3>
						<div class="medium-6 columns remove-padding-sides">
							<%= form_for(Vote.new(user: current_user, route_id: @route.id, score: 1 )) do |f| %>
									<div class="field">
									  <%= f.hidden_field :user_id %>
									  <%= f.hidden_field :route_id %>
									  <%= f.hidden_field :score %>
									</div>

									<div class="actions"> 

											 <button class="expand"  type="submit" >
													<%= fa_icon "thumbs-o-up" %>&nbsp;&nbsp;&nbsp;  Awesome! 
											 </button>
									</div>							
							<% end %>
					</div>

				
					<div class="medium-6 columns remove-padding-sides">
						<%= form_for(Vote.new(user: current_user, route_id: @route.id, score: -1 )) do |f| %>
								<div class="field">
								  <%= f.hidden_field :user_id %>
								  <%= f.hidden_field :route_id %>
								  <%= f.hidden_field :score %>
								</div>

								<div class="actions">
								  <button class="expand" type="submit" >
										<%= fa_icon "thumbs-o-down" %>&nbsp;&nbsp;&nbsp; Boooooh! 
									</button>
								</div>
						<% end %>

					</div>
				</div>
			</div>



				<div class="route-desc-phone small-12 columns">
					<hr>
					<p> <%= @route.description %> </p>
				</div>	

			<div class="fb_comments small-12 medium-6 large-6 columns">
				<%= render "/layouts/fb_comments" %>
			</div>
	</div>	




			


























			<%-# comment -%>
			<% if false %>

				Overall Votes: <%= @route.score %>  
				Positive Votes: <%= @route.positive_votes %> 
				Negative Votes: <%= @route.negative_votes %> 

	          <%= link_to 'Edit', edit_stop_path(stop) %>
	          
			  <%= link_to 'Delete Stop', stop, method: :delete, data: { confirm: 'Are you sure?' } %>
				<p> 
					Category: 
					<% stops.categories.each do |category| %>
						<%= category.name %>
					<% end %>
				</p>
				<p> Stop ID: <%= stops.id %>  </p>
				<p> Stop name :<%= stops.name %>  </p>
				<p> Stop description :<%= stops.description %> </p>
				<p> Stop lat :<%= stops.stop_lat %>  </p>
				<p> Stop long:<%= stops.stop_long %>  </p>
			<% end %>
			<%-# comment -%>
























	<% if current_user.present? and current_user.admin? %>

		<div class="row ">
		<h2>Create a new stop:</h2><br>
		<%= form_for(@stop) do |f| %>
		  <% if @stop.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(@stop.errors.count, "error") %> prohibited this stop from being saved:</h2>
		      <ul>
		      <% @stop.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		      </ul>
		    </div>
		  	<% end %>
		 	<div class="field">
			    <%= f.label :name %><br>
			    <%= f.text_field :name %>
		 	</div>
			
			<select name="category" id=" " >
			  	
			  	<option value="" disabled selected> Select a Category </option>

			  	<% @categories.each do |category| %>
			  	<option value="<%= category.id %>"> <%= category.name %> </option>
				<% end %>
			</select>
		 	
		 	<div class="field">
			    <%= f.label :description %><br>
			    <%= f.text_area :description %>
		 	</div>
			

			<div class="field">
			    <%= f.label :stop_image %><br>
			    <%= f.file_field :stop_image %>
			</div>

			<div class="field">
			    <%= f.label :stop_lat %><br>
			    <%= f.number_field :stop_lat, :class => 'text_field', :step => 'any' %>
			</div>
			<div class="field">
			    <%= f.label :stop_long %><br>
			    <%= f.number_field :stop_long, :class => 'text_field', :step => 'any' %>
			</div>

				<%= hidden_field_tag  :route_id,  params[:id]    %>
			<div class="actions">
			    <%= f.submit %>
			</div>
		<% end %> 


		<h2>Add existing stop</h2>
		<br>
		<%= form_for(@waypoint) do |f| %>
			<div class="field">
			    <%= f.label :stop_id %><br>
			    <%= f.number_field :stop_id %>
		 	</div>
			<%= f.hidden_field  :route_id    %>
			
			<div class="actions">
			    <%= f.submit %>
			</div>
		<% end %> 

		<%= link_to 'Edit', edit_route_path(@route) %> |
		<%= link_to 'Back', routes_path %>
		<br>
		<br>
		<br>
			</div>
		

	<% end %>


	</div>

</div>
</div>			